### ISSUE TITLE
set jtag speed issue

### ISSUE THREAD

**Issue by primeordinalsoup** [pavelrevak/pyswd#1]
firstly thanks what a splendid piece of tidy python!

i found that it was not setting the jtag speed as expected because the hash is unordered.  i made a fix, do you want a pull request for it?

**Comment by pavelrevak** [comment]
Hello and thanks,
Of course, your pull request will be welcome.

**Comment by pavelrevak** [comment]
I have changed dict to tuple, is better, dict is useless in this case.
